name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller>=5.0
        python -m pip install requests>=2.25.0

    - name: Run CI tests
      run: |
        python main_ci.py
      env:
        # 设置环境变量以支持无头模式
        PYTHONUNBUFFERED: 1
        CI: true

  build:
    needs: test
    runs-on: windows-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller>=5.0

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name=FileMover main_ci.py
      env:
        # 设置环境变量以支持无头构建
        PYTHONUNBUFFERED: 1
        CI: true

    - name: Verify build
      run: |
        if (Test-Path "dist\FileMover.exe") {
          Write-Host "✅ Build successful"
          Get-Item "dist\FileMover.exe" | Select-Object Name, Length
        } else {
          Write-Host "❌ Build failed"
          exit 1
        }

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: FileMover-Build
        path: dist/FileMover.exe
        retention-days: 7
